services:
  db:
    image: postgres:15
    container_name: flask_postgres_db
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: